#!/usr/bin/env python3
"""Advisory documentation review for a pull request.

Reads a diff of docs/ from stdin, asks a model to review it, and posts the result as a
pull request comment. Advisory only - the workflow that calls this never fails the build.

Deliberately does not check anything the deterministic gates already cover. Vale checks
banned terms and punctuation, markdownlint checks structure, lychee checks links, and the
Docusaurus build checks that the site compiles. Repeating those here would produce noise
and teach the reader to skim the comment.
"""

import json
import os
import sys
import urllib.request

MODEL = "claude-haiku-4-5-20251001"
MAX_DIFF_CHARS = 60000

PROMPT = """You are reviewing a change to a documentation site. The site documents a cloud
security product called Ridgeline, and its pages are written for a security engineer who has
opened a report and needs to decide what to do next.

Review the diff below and comment only on things a human reviewer would raise. Be specific,
cite the file and the line, and keep the whole comment under 300 words.

Look for:

- A claim stated as fact that the diff gives no source for. The repository convention is to
  mark unverified claims `[VERIFY: what needs confirming]` rather than asserting them.
- A page that has stopped serving its stated purpose - for example a procedure that explains
  a screen instead of telling the reader what to do.
- A term used in more than one sense within the change, or a term introduced without
  explanation.
- A statement that contradicts something else in the diff.
- An instruction the reader could not act on, because it names no control, or no outcome.

Do not comment on:

- Spelling, punctuation, capitalisation, banned words, or heading spacing. Automated checks
  already cover all of these, and repeating them wastes the reader's attention.
- Broken links or missing images. A link checker covers those.
- Style preferences. Say what is wrong, not what you would have written.

If the change is fine, say so in one sentence and stop. A short comment that says nothing is
wrong is more useful than a long one that pads.

Diff:

```diff
{diff}
```
"""


def call_api(diff: str) -> str:
    key = os.environ["ANTHROPIC_API_KEY"]
    body = json.dumps({
        "model": MODEL,
        "max_tokens": 1000,
        "messages": [{"role": "user", "content": PROMPT.replace("{diff}", diff)}],
    }).encode()

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "content-type": "application/json",
            "x-api-key": key,
            "anthropic-version": "2023-06-01",
        },
    )
    with urllib.request.urlopen(req, timeout=120) as r:
        data = json.load(r)

    return "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text")


def post_comment(text: str) -> None:
    token = os.environ["GITHUB_TOKEN"]
    repo = os.environ["GITHUB_REPOSITORY"]
    pr = os.environ["PR_NUMBER"]

    comment = (
        "## Advisory documentation review\n\n"
        f"{text}\n\n"
        "---\n\n"
        f"*Generated by `{MODEL}`. Advisory only - this check never blocks a merge, and "
        "disagreeing with it is a legitimate outcome. Style, structure, and links are "
        "checked by the deterministic gates instead.*"
    )

    req = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/issues/{pr}/comments",
        data=json.dumps({"body": comment}).encode(),
        headers={
            "authorization": f"Bearer {token}",
            "accept": "application/vnd.github+json",
            "content-type": "application/json",
        },
    )
    urllib.request.urlopen(req, timeout=60)


def main() -> int:
    diff = sys.stdin.read()

    if not diff.strip():
        print("No changes under docs/. Nothing to review.")
        return 0

    if len(diff) > MAX_DIFF_CHARS:
        diff = diff[:MAX_DIFF_CHARS] + "\n\n[diff truncated]"

    try:
        review = call_api(diff)
    except Exception as e:
        print(f"Review call failed: {e}")
        return 0

    if not review.strip():
        print("Model returned nothing. Skipping comment.")
        return 0

    try:
        post_comment(review)
        print("Comment posted.")
    except Exception as e:
        print(f"Could not post comment: {e}")

    return 0


if __name__ == "__main__":
    sys.exit(main())