// @ts-check
// Sidebar structure is curated here, in code. Docs not listed (or not matched by
// an autogenerated entry) do not appear in the nav.
// Frontmatter sidebar_position controls ordering within autogenerated categories.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'index',
  ],
};

export default sidebars;
