// @ts-check
// Sidebar structure is curated here, in code. Docs not listed (or not matched by
// an autogenerated entry) do not appear in the nav.
// Frontmatter sidebar_position controls ordering within autogenerated categories.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Unused Access',
      items: [
        'unused-access-report',
        'about-the-access-tab',
        'apply-a-remediation',
      ],
    },
    {
      type: 'category',
      label: 'About this project',
      items: [
        'what-changed',
        {
          type: 'category',
          label: 'Marketing work sample',
          link: {type: 'doc', id: 'marketing-work-sample'},
          items: [
            'marketing-work-sample/landing-page',
            'marketing-work-sample/blog-post',
            'marketing-work-sample/one-pager',
          ],
        },
        'pipeline-and-ai-terms',
      ],
    },
  ],
};

export default sidebars;
