// @ts-check
// Sidebar structure is curated here, in code. Docs not listed (or not matched by
// an autogenerated entry) do not appear in the nav.
// Frontmatter sidebar_position controls ordering within autogenerated categories.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Unused Access',
      items: [
        'unused-access-report',
        'about-the-access-tab',
        'apply-a-remediation',
      ],
    },
    {
      type: 'category',
      label: 'About this project',
      items: [
        'what-changed',
        'pipeline-and-ai-terms',
        'design-system',
      ],
    },
  ],
};

export default sidebars;
